final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   path('admin/', admin.site.urls),
#    path('accounts/', include('django.contrib.auth.urls')),
   path('', include('medic_app.urls')),
#    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

# # for the images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medic_app/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from .views import RegisterPage, CustomLoginView, logout_user
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

app_name = "medic_app"

urlpatterns = [
   path('login/', CustomLoginView.as_view(), name='login'),
   path('logout/', views.logout_user, name='logout'),
   path('register/', RegisterPage.as_view(), name='register'),
   path('', views.index, name='index'),
   
   path('search/', views.search, name='search'),
   path('saved/', views.saved, name='saved'),
   path('profile/<int:pk>/', views.profile_details, name='profile'),
]

medic_app/models.py
from __future__ import annotations
from django.db import models, transaction
from django.contrib.auth.models import User
from django.db.models import Q
from django.db.models.query import QuerySet
from django.conf import settings
from django_countries.fields import CountryField



class Location(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.PROTECT)
    country = CountryField(blank_label='(select country)')

    def __str__(self):
        return f'{self.pk}: {self.country}'


class Drug(models.Model):
    name = models.CharField(max_length=200, db_index=True, blank=True, null=True)
    country= CountryField(blank_label='(select country)')
    main_agent_1 = models.CharField(max_length=200, db_index=True, blank=True, null=True)   
    dose = models.IntegerField(db_index=True, blank=True, null=True)
    unit = models.CharField(max_length=200, db_index=True, blank=True, null=True)
    image = models.ImageField(blank="True", upload_to='media')

    def __str__(self):
        return f'{self.pk}:{self.name}:{self.country}:{self.main_agent_1}:{self.dose}:{self.unit}:{self.image}'


class Favourite(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    drug = models.ForeignKey(Drug, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.pk}:{self.user}:{self.drug}'

medic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import Location


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

class LocationForm(forms.ModelForm):
    country = forms.CharField(label='Country')

    class Meta:
        model = Location
        fields = ('country',)

class NewUserForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ('country',)

medic_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.urls import path, reverse, reverse_lazy
from django.http import HttpResponseRedirect

from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

from .models import Drug, User, CountryField, Location
from .forms import UserForm, LocationForm, NewUserForm, NewUserForm
from django.db.models import Q



class CustomLoginView(LoginView):
   template_name = 'medic_app/login.html'
   fields = '__all__'
   redirect_authenticated_user = True

   def login_user(request):
      return render(request, 'medic_app/login.html', {})


def logout_user(request):
   logout(request)
   return redirect('medic_app:login')



class RegisterPage(FormView):
   template_name = 'medic_app/register.html'
   form_class = UserCreationForm
   redirect_authenticated_user = True
   success_url = reverse_lazy('medic_app:index')

   def form_valid(self, form):
      user = form.save()
      if user is not None:
         login(self.request, user)
      return super(RegisterPage, self).form_valid(form)


# class DrugList(LoginRequiredMixin, ListView):
#    model = Drug
#    context_object_name = 'saved'
   
#    def get_context_data(self, **kwargs):
#       context = super().get_context_data(**kwargs)
#       context['drugs'] = context['drugs'].filter(user=self.request.user)
#       return context


def index(request):
   if request.user.is_authenticated:
      user = request.user
      drugs = Drug.objects.all
      location_form = LocationForm(request.POST, instance=user.location)
      context = {
         'drugs': drugs,
         'location_form': location_form,
      }
      return render(request, 'medic_app/index.html', context)
   else:
      return HttpResponseRedirect(reverse('medic_app:login'))

# def index(request, pk):
#    if request.user.is_authenticated:
#       return HttpResponseRedirect(reverse('medic_app:index'))
#    else:
#       return HttpResponseRedirect(reverse('medic_app:login'))


# def index(request, pk):
#    user = get_object_or_404(User, pk=pk)
#    if user.is_authenticated:
#       drugs = Drug.objects.all
#       location_form = LocationForm(request.POST, instance=user.location)
#       context = {
#          'drugs': drugs,
#          'location_form': location_form,
#       }
#       return render(request, 'medic_app/index.html', context)



def search(request):
   if request.method == "POST":
      current_user = request.user.location
      countries = CountryField()
      searched = request.POST.get('searched', False)
      try:
         searched_drugs = Drug.objects.get(name__contains=searched)
         drugs = Drug.objects.filter(main_agent_1=searched_drugs.main_agent_1, country=current_user.country)
      except Drug.DoesNotExist:
         searched_drugs = False
         drugs = False
      except Drug.MultipleObjectsReturned:
         searched_drugs = False
         drugs = False
      return render(request, 'medic_app/search_result.html', {'searched': searched, 'drugs': drugs, 'countries': countries,})
   else:
      return render(request, 'medic_app/search_result.html', {})



def profile_details(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'GET':
        user_form = UserForm(instance=user)
        location_form = LocationForm(instance=user.location)
    elif request.method == 'POST':
       user_form = UserForm(request.POST, instance=user)
       location_form = LocationForm(request.POST, instance=user.location)
       if user_form.is_valid() and location_form.is_valid():
            user_form.save()
            location_form.save()
    new_user_form = NewUserForm()
    context = {
         'user': user,
         'user_form': user_form,
         'location_form': location_form,
         'new_user_form': new_user_form,
    }
    return render(request, 'medic_app/profile.html', context)

# @login_required
# def updated_user(request, user):
#     if request.method == 'POST':
#         new_user_form = NewUserForm(request.POST)
#         if new_user_form.is_valid():
#             Account.objects.create(user=User.objects.get(pk=user), name=new_account_form.cleaned_data['name'])
#     return HttpResponseRedirect(reverse('bank:staff_customer_details', args=(user,)))


    
def saved(request):
   return render(request, 'medic_app/drug_list.html', {})

medic_app/templates/medic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100&display=swap" rel="stylesheet">
   {% load static %}
   <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" media="screen" />
   <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
   
   <title>Medigi</title>
</head>

<body>
    <div id="splash">
        <img src="{% static 'img/logo.png' %}" alt="" class="logo">
        <p>Medigi</p>
    </div>
    <div class="content">
        <header class="app-header">
            <div class="user-login-logout">
                {% if request.user.is_authenticated %}
                <div class="user-welcome">
                    <p>Welcome {{request.user}}!</p>
                </div>
                <div class="container">
                    <img src="{% static 'img/logo.png' %}" alt="" class="logo">
                    <p id="brand-name">Medigi</p>
                    <!-- <p id="motto">A pharmacist in your pocket.</p>   -->
                </div>
                <div class="login-logout">
                    <a href="{% url 'medic_app:logout' %}">Logout</a>
                </div>
                {% else %}
                <div class="container">
                    <img src="{% static 'img/logo.png' %}" alt="" class="logo">
                    <p id="brand-name">Medigi</p>
                    <!-- <p id="motto">A pharmacist in your pocket.</p>   -->
                </div>
                <div class="login-logout">
                    <a href="{% url 'medic_app:login' %}">Login</a>
                </div>
                {% endif %}
            </div>
            
        </header>
        {% block main %}
        {% endblock %}    

    </div>

    <footer class="app-footer">
        <ul>
            <a class="data-tabs" href="{% url 'medic_app:index' %}">
                <li class="tab is_active">
                    <i class="fa fa-home"></i>
                    Home
                </li>
            </a>
            <a class="data-tabs" href="">
                <li class="tab">
                    <i class="fa fa-heart"></i>
                    Saved
                </li>
            </a>
            {% if request.user.is_authenticated %}
            <a class="data-tabs" href="{% url 'medic_app:profile' user.pk %}">
                <li class="tab">
                    <i class="fa fa-user"></i>
                    Profile
                </li>
            </a>
            {% else %}
            <a class="data-tabs" href="">
                <li class="tab">
                    <i class="fa fa-user"></i>
                    Profile
                </li>
            </a>
            {% endif %}

            <a class="data-tabs" href="">
                <li class="tab">
                    <i class="fa fa-map-marker"></i>
                    Find Store
                </li>
            </a>
        </ul>
    </footer>
    
    <script>
        setTimeout(() => {
        document.getElementById('splash').classList.toggle('fade')
        }, 500);
        
        function changeFlag() {
            var flag = document.getElementById("myLocation").value;
            console.log(flag);
            {% verbatim %}
            console.log('{% static "img/' + flag + '.svg" %}');
            document.getElementById("myFlag").src = "/static/img/" + flag + ".svg";
            {% endverbatim %}
            
        }

        function selectCountry() {
            var country = document.getElementById("myLocation").value;
            // document.getElementById("selected").innerHTML = country;
            changeFlag();
        }

        window.onload = () => {
            const tab_switchers = document.querySelectorAll('.data-tabs');
            for (let i = 0; i < tab_switchers.length; i++) {
                const tab_switcher = tab_switchers[i];
                
                tab_switcher.addEventListener('click', () => {
                    document.querySelector('.tab.is_active').classList.remove('is_active');
                    tab_switcher.classList.add('is_active');

                })
            }
        }
    </script>
    
    </body>
    </html>

medic_app/templates/medic_app/drug_list.html
{% extends "medic_app/base.html"%}

{% block main %}
	<div class="search-filter">
		<div class="filter">
		<img src="https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg" alt="">
		<i class="fa fa-arrow-right"></i>
		<img src="https://upload.wikimedia.org/wikipedia/commons/8/89/Bandera_de_Espa%C3%B1a.svg" alt="">
		</div>
		<form action="{% url 'medic_app:search' %}" method="POST">
		{% csrf_token %}
		<input type="search" class="search form-control" name="searched" placeholder="Search drugs">
		<button>Search</button>
		</form>  
	</div>

	<div class="search-grid container">

        <div class="medicine-item">
			<div class="medicine-img">
				<img src="https://www.nicepng.com/png/detail/776-7767361_nurofen.png" alt="">
			</div>
		  <h4>Nurofen Forte</h4>
		  <div class="card-bottom">
			<p>Fast pain relief, lowers fever, treats inflamation</p>
			<div class="save-button">
				<i class="fa fa-heart"></i>
			</div> 
		  </div>  
		</div>
        
		<div class="medicine-item">
			<div class="medicine-img">
				<img src="https://www.brufen.com/content/dam/bss/divisionalsites/brufen/kw/en/images/new-BRUFEN-400-Pack-updated.png" alt="">
			</div>
		  <h4>Brufen 400</h4>
		  <div class="card-bottom">
			<p>Fast pain relief, lowers fever, treats inflamation</p>
			<div class="save-button">
				<i class="fa fa-heart"></i>
			</div> 
		  </div>
		</div>

	</div>

{% endblock %}

medic_app/templates/medic_app/index.html
{% extends "medic_app/base.html"%}
{% block main %}

    <div class="search-filter">
      <div class="filter">
        <img src="https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg" alt="">
        <i class="fa fa-arrow-right"></i>
        {% load static %}
        <img id="myFlag" src="{% static 'img/ES.svg' %}" alt=""><span id="selected"></span>
        <select id="myLocation" onchange="selectCountry()">
          <option value="ES" selected>{{user.location}}</option>
          <option value="HU" >HU</option>
          <option value="DE" >DE</option>
        </select>
      </div>
      <form action="{% url 'medic_app:search' %}" method="POST">
        {% csrf_token %}
        <input type="search" class="search form-control" name="searched" placeholder="Search drugs">
        <button>Search</button>
      </form>  
    </div>
    
    <div class="grid container">

      <a href="">
        <div class="item left-diagon box-1" id="box-1">
          <h4>History</h4>
          <img src="https://i.ibb.co/BKgzCc5/medicine.png" alt="">
        </div>
      </a> 
      {% if request.user.is_authenticated %}
      <a href="{% url 'medic_app:profile' user.pk %}">
        <div class="item right-diagon" id="box-2">
          <h4>Profil</h4>
          <img src="https://www.pngall.com/wp-content/uploads/5/Profile-Male-PNG.png" alt="">
        </div>
      </a>
      {% else %}
      <a href="">
        <div class="item right-diagon" id="box-2">
          <h4>Profil</h4>
          <img src="https://www.pngall.com/wp-content/uploads/5/Profile-Male-PNG.png" alt="">
        </div>
      </a>
      {% endif %}

      <a href="">
        <div class="item right-diagon" id="box-3">
          <h4>Saved drugs</h4>
          <img src="https://i.ibb.co/XY6WTq6/medal.png" alt="">
        </div>
      </a>
      
      <a href="">
        <div class="item left-diagon" id="box-4">
          <h4>Find store</h4>
          <img src="https://www.pngall.com/wp-content/uploads/5/Google-Maps.png" alt="">
        </div>
      </a>
    </div>
{% endblock %}

medic_app/templates/medic_app/login.html
{% extends "medic_app/base.html" %}

{% block main %}
<div class="login-form">
    <h1>Login</h1>
    <form action="{% url 'medic_app:login' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="login-button" type="submit" value="Login">
    </form>
    <p>Don't have an account? <a href="{% url 'medic_app:register' %}">Register</a></p>
</div>

{% endblock main %}

medic_app/templates/medic_app/password_change.html
{% extends "base.html" %}

{% block main %}

<form action="{% url 'password_change' %}" method="POST">
    <fieldset>
        <legend>Please change your password</legend>
        {% csrf_token %}
        <!--<input type="text" name="username" placeholder="User name">-->
        <input type="password" name="password" placeholder="Password">
        <button>Submit</button>
    </fieldset>
</form>
{% endblock main %}

medic_app/templates/medic_app/password_change_done.html
<h1>Password changed</h1>
  <a href="{% url 'login' %}">Log back in with your new password</a>

medic_app/templates/medic_app/profile.html
{% extends "medic_app/base.html" %}

{% block main %}

<div class="login-form">
    <div class="profile-img">
        <img src="" alt="">
    </div>
    <h3>Your Details</h3>

    <form action="{% url 'medic_app:profile' user.pk %}" method="POST" id="profile-form">
        {% csrf_token %}
        <fieldset>
            {{ user_form.as_p }}
            <p style="display:inline">In{{location_form}}</p>
        <button>Update User</button>
        </fieldset>
    </form>
    
</div>

{% endblock main %}

medic_app/templates/medic_app/register.html
{% extends "medic_app/base.html" %}

{% block main %}
<div class="login-form" id="register-form">
    <h1>Register</h1>
    <form action="{% url 'medic_app:register' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="login-button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{% url 'medic_app:login' %}">Login</a></p>
</div>

{% endblock main %}

medic_app/templates/medic_app/search_result.html
{% extends "medic_app/base.html"%}

{% block main %}
	<div class="search-filter">
		<div class="filter">
			<img src="https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg" alt="">
			<i class="fa fa-arrow-right"></i>
			{% load static %}
        	<img id="myFlag" src="{% static 'img/ES.svg' %}" alt=""><span id="selected"></span>
        	<select id="myLocation" onchange="selectCountry()">
          		<option value="ES" selected>{{user.location}}</option>
          		<option value="HU" >HU</option>
          		<option value="DE" >DE</option>
        	</select>
		</div>
		<form action="{% url 'medic_app:search' %}" method="POST">
		{% csrf_token %}
		<input type="search" class="search form-control" name="searched" placeholder="Search drug">
		<button>Search</button>
		</form>  
	</div>
	
	<div class="search-grid container">
		{% if searched %}
			{% if drugs %}
				<div class="search-info">
					<p>Alternatives for {{ searched }} in <span class="bold">{{ user.location.country.name }}</span></p>
				</div>
				{% for drug in drugs %}
				<div class="medicine-item">
					<div class="medicine-img">
						<img src="{{ drug.image }}" alt="">
					</div>
					<h4>{{ drug.name }}</h4>
					<div class="card-bottom">
						<p>{{ drug.main_agent_1 }}</p>
						<div class="save-button">
							<i class="fa fa-heart"></i>
						</div> 
				</div>
				</div>
				{% endfor %}
			{% else %}
				<div class="search-info">
					<p>Couldn't find any alternatives :(</p>
				</div>
			{% endif %}

		{% else %}
			<div class="search-info">
				<p>I don't know what you mean :(</p>
			</div>
		{% endif %}
  
	</div>

{% endblock %}